# ==============================================================================
# General settings
# ==============================================================================
# plugin manager
[[plugins]]
repo = 'Shougo/dpp.vim'
depends = ['denops.vim']
# An ecosystem of Vim/Neovim which allows developers to write plugins in Deno
[[plugins]]
repo = 'vim-denops/denops.vim'
# switch between commmentout and uncomment
[[plugins]]
repo = 'tomtom/tcomment_vim'
# auto save on normal mode
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = 'source ~/.config/nvim/plugins/vim-auto-save.vim'
# auto close parentheses
[[plugins]]
repo = 'cohama/lexima.vim'
# Restore cursor position
[[plugins]]
repo = 'ethanholz/nvim-lastplace'
# All-in-one plugin
[[plugins]]
repo = 'nvim-mini/mini.nvim'
# ==============================================================================
# GUI settings
# ==============================================================================
# File source for ddu.vim ++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Dark deno-powered UI framework for neovim/Vim8
[[plugins]]
repo = 'Shougo/ddu.vim'
hook_add = 'source ~/.config/nvim/plugins/ddu.vim'
# source
[[plugins]]
repo = 'Shougo/ddu-source-file'
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
# kind
[[plugins]]
repo = 'Shougo/ddu-kind-file'
# Icon and filename column for ddu.vim
[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
# File listing UI for ddu.vim
[[plugins]]
repo = 'Shougo/ddu-ui-filer'
# fzf for ddu
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
[[plugins]]
repo = 'shun/ddu-source-rg'
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# iceberg theme for vim
[[plugins]]
repo = 'cocopon/iceberg.vim'
# Graphical icons for nvim in lua
[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'
# decorate status line
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = 'source ~/.config/nvim/plugins/lualine.nvim.lua'
[[plugins]]
repo = 'pnx/lualine-lsp-status'
# show and colorize indent levels
[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
hook_add = 'source ~/.config/nvim/plugins/indent-blankline.nvim.lua'
# highlights code using tree-sitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
# Highly experimental plugin that completely replaces the UI for messages, cmdline and the popupmenu.
[[plugins]]
repo = 'folke/noice.nvim'
[[plugins]]
repo = 'miteshP/nvim-navic'
depends = 'nvim-lspconfig'
hook_add = 'source ~/.config/nvim/plugins/noice.nvim.lua'
# Highlight arguments' definitions and usages, asynchronously, using Treesitter.
[[plugins]]
repo = 'm-demare/hlargs.nvim'
hook_add = 'source ~/.config/nvim/plugins/hlargs.nvim.lua'
# Plugin to improve viewing Markdown files in Neovim
[[plugins]]
repo = 'MeanderingProgrammer/render-markdown.nvim'
depends = ['nvim-treesitter', 'mini.nvim']
hook_add = 'source ~/.config/nvim/plugins/render-markdown.nvim.lua'
# colorize color code
[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
hook_source = 'source ~/.config/nvim/plugins/nvim-colorizer.nvim.lua'
[[plugins]]
repo = 'shellRaining/hlchunk.nvim'
hook_source = 'source ~/.config/nvim/plugins/hlchunk.nvim.lua'
# ==============================================================================
# Completion settings
# ==============================================================================
# Portable package manager for Neovim
[[plugins]]
repo = 'williamboman/mason.nvim'
hook_add = 'source ~/.config/nvim/plugins/mason.nvim.lua'
# LSP configurations for Neovim
[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = 'source ~/.config/nvim/plugins/nvim-lspconfig.nvim.lua'
# mason-lspconfig bridges mason.nvim with the lspconfig plugin
[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
hook_add = 'source ~/.config/nvim/plugins/mason-lspconfig.nvim.lua'
# Lightweight yet powerful formatter plugin for Neovim
[[plugins]]
repo = 'stevearc/conform.nvim'
hook_add = 'source ~/.config/nvim/plugins/conform.nvim.lua'
# github copilot
[[plugins]]
repo = 'github/copilot.vim'
hook_add = 'source ~/.config/nvim/plugins/copilot.lua'
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# File source for ddc.vim
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
hook_add = 'source ~/.config/nvim/plugins/ddc.vim'
# nvim-lsp completion for ddc.vim
[[plugins]]
repo = 'Shougo/ddc-source-lsp'
hook_add = 'source ~/.config/nvim/plugins/ddc-nvim-lsp-setup.lua'
# Framework library to implement original popup menu completion.
[[plugins]]
repo = 'Shougo/ddc-ui-pum'
[[plugins]]
repo = 'Shougo/pum.vim'
# github copilot for ddc
[[plugins]]
repo = 'Shougo/ddc-source-copilot'
hook_source = 'source ~/.config/nvim/plugins/ddc-source-copilot.lua'
# ui settings for ddc
[[plugins]]
repo = 'Shougo/ddc-ui-native'
# Source for completion existing words around the cursor. 
[[plugins]]
repo = 'Shougo/ddc-source-around'
# Filter for completion of words as they are being typed.
[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'
# Filter to properly sort candidate completions.
[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'
# file completions for ddc.vim
[[plugins]]
repo = 'LumaKernel/ddc-file'
# mocword completion for ddc.vim: requirement(https://github.com/high-moctane/mocword)
[[plugins]]
repo = 'Shougo/ddc-mocword'
# Filter to prevent duplication of candidate completions
[[plugins]]
repo = 'Shougo/ddc-source-cmdline_history'
[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
# Show completion documentation
[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_add = 'source ~/.config/nvim/plugins/denops-popup-preview.vim'
# Shows signature help from lsp server.
[[plugins]]
repo = 'matsui54/denops-signature_help'
hook_add = 'source ~/.config/nvim/plugins/denops-signature_help.vim'
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
