# ==============================================================================
# 遅延読み込みプラグイン
# ==============================================================================
# nvim-transparent: 背景を透過させてNeovimを透明にするプラグイン
[[plugins]]
repo = 'xiyaowong/nvim-transparent'
on_event = 'BufEnter'
# hook_source = 'source ~/.config/nvim/plugins/nvim-transparent.nvim.lua'
